# Generated by Django 3.1 on 2020-08-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_brand', models.CharField(max_length=20)),
                ('p_name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('size_1', models.IntegerField()),
                ('size_2', models.IntegerField()),
                ('size_3', models.IntegerField()),
                ('size_4', models.IntegerField()),
                ('size_5', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
    ]
