# Generated by Django 3.1 on 2020-08-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='picture')),
                ('brand', models.CharField(max_length=20)),
                ('percentage', models.CharField(max_length=20)),
            ],
        ),
    ]
