# Generated by Django 3.1 on 2020-09-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_registerform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registerform',
        ),
    ]
