# Generated by Django 3.1 on 2020-09-11 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='productname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='productquantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='productsize',
        ),
    ]
