# Generated by Django 3.1 on 2020-09-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20200911_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='productname',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='productquantity',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='productsize',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
